upstream client {
    server client:3000;
}

upstream api {          # changed 'server' to 'api' to make it less confusing
    server api:5000;
}

server {
    listen 80;

    location / {        # '/' is directed to client
        proxy_pass http://client;
    }

    location /ws {
        proxy_pass http://client;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    } # dev specific piece of conf


    location /api {     # '/api' is directed to server
        rewrite /api/(.*) /$1 break;    # cuts off the /api before passing to express server
                                        # '$1' matches '(.*)'
                                        # break: no more rewrite rules
        proxy_pass http://api;          
    }
}

